export enum BotsTags{
  anime = 'anime',
  dashboard = 'dashboard',
  diversao = 'diversao',
  utilidades = 'utilidades',
  social = 'social',
  jogos = 'jogos',
  musica = 'musica',
  moderacao = 'moderacao',
  economia = 'economia',
  nsfw = 'nsfw',
  outros = 'outros'
}

export enum AppLibrary{
  discordjs = 'discord.js',
  discordpy = 'discord.py',
  discordCr = 'discordCr',
  discordio = 'discord.io',
  eris = 'eris',
  restCord = 'RestCord',
  discordia = 'discordia',
  nxy = 'nxy',
  serenity = 'serenity',
  discordie = 'discordie',
  discordPhp = 'DiscordPHP',
  sword = 'Sword',
  discordUnity = 'DiscordUnity',
  litcord = 'litcord',
  discordhs = 'discord-hs',
  discordrb = 'discordrb',
  discordNet = 'Discord.Net',
  jda = 'JDA',
  javaCord = 'Javacord',
  dSharpPlus = 'DSharpPlus',
  dscord = 'dscord',
  discordGo = 'DiscordGo',
  disGord = 'DisGord',
  discord4j = 'Discord4j',
  discordnim = 'discordnim',
  yasmin = 'Yasmin',
  disco = 'disco',
  ackCord = 'AckCord',
  botDesigner = 'Bot Designer',
  dbm = 'DBM',
  outro = 'Outro'
}
